# Title

In [ ]:
name = input("name:").title()
bday = input("bday:")
email = input("email:")

print(name, bday, email, sep="\n")

Keene
Lu
11/24
klu@email.com


In [10]:
def get_info():
    f_name = input("first name:").title()
    l_name = input("last name:").title()
    bday = input("bday:")
    email = input("email:")

    print(f_name, l_name, bday, email, sep="\n")

get_info()

Keene
Lu
11/24
klu@email.com


In [12]:
raw_username = " Py_Thon-ROCKS123"

username = raw_username.strip().lower().replace("-", "_").replace("!", "")

has_digit = any(char.isdigit() for char in username)
contains_python = "python" in username
first_eight = username[0:8]
print(f"Username: {username}, contains a digit: {has_digit}, contains 'python': {contains_python}, first 8 chars: {first_eight}")


Username: py_thon_rocks123, contains a digit: True, contains 'python': False, first 8 chars: py_thon_


In [13]:
students = [('alice',34),('bob',22),('diana',19)]

students.sort(key=lambda student: student[1], reverse = True)
print(students)

[('alice', 34), ('bob', 22), ('diana', 19)]


In [14]:
students = [("Alice", 20, "A"), ("Bob", 19, "B"), ("Charlie", 21, "A"),("Diana", 20, "C")]
# Print only students with an 'A'
[print(student) for student in students if student[2] == "A"]
print("===")
# Print all names
[print(student[0]) for student in students]
print("===")
# Give all 20yo a 'B' then print list
print( [ tuple(["B" if x == student[2] else x for x in student]) if student[1] == 20 else student for student in students])
# alternative method
print( [ (name, age, "B") if age == 20 else (name, age, grade) for (name, age, grade) in students])


('Alice', 20, 'A')
('Charlie', 21, 'A')
===
Alice
Bob
Charlie
Diana
===
[('Alice', 20, 'B'), ('Bob', 19, 'B'), ('Charlie', 21, 'A'), ('Diana', 20, 'B')]
[('Alice', 20, 'B'), ('Bob', 19, 'B'), ('Charlie', 21, 'A'), ('Diana', 20, 'B')]


In [20]:
attendees = ["Alice", "Bob", "Alice", "Ethan", "Bob", "Diana", "Ethan", "Frank"]
# 1
attendees_set = set(attendees)
print(f"Total attendiees: {len(attendees_set)}")
if "Alice" in attendees_set:
    print("Alice is going")
attendees_set.add("Grace")
attendees_set.discard("Bob")
attendees_set.discard("Bob")
print(attendees_set)

Total attendiees: 5
Alice is going
{'Diana', 'Alice', 'Ethan', 'Grace', 'Frank'}


In [21]:

import os

bids = {}

def get_bid():
    global bids
    name = input("Name: ")
    bid = int(input("bid amount: $"))
    os.system('cls')
    bids[name] = bid

bidders = True
highest_bid = ["", 0]
while bidders:
    get_bid()
    more_bids = input("Any more bidders? (y/n): ")
    if more_bids.lower() == "n":
        break
print(bids)

for bidder, bid in bids.items():
    if bid > highest_bid[1]:
        highest_bid[1] = bid
        highest_bid[0] = bidder

print(f"{highest_bid[0]} won the auction with a bid of ${highest_bid[1]}")


{'qwer': 1234, 'qwertyuioop': 122222222, 'asdfgh': 1222}
qwertyuioop won the auction with a bid of $122222222


In [19]:
import numpy as np

arr1 = np.array([[[1,2], [3,4]], [[4,3],[2,1]]])
arr2 = np.array([[[5,6], [7,8]], [[8,7],[6,5]]])
arr = np.concatenate((arr1,arr2), axis = 2)
print(arr)

[[[1 2 5 6]
  [3 4 7 8]]

 [[4 3 8 7]
  [2 1 6 5]]]


In [ ]:
from random import randint

#heads: dict, tails: list

coin_toss = randint(0, 1)


match coin_toss:
    case 0:
        # "heads"
        dictionary = {
            "Name1" : "stuff",
            "Name2" : "stuff2"
        }
    case 1:
        # "tails"
        licticle = [
            1,2,3,4
        ]




In [ ]:
# #####################################
# # CHALLENGE: Clean data with Pandas # 
# #####################################

import pandas as pd
import numpy as np
import re
from book_generator_bad_data_service import generate_bad_books


# generate_bad_books()

df = pd.read_json("books_dirty.json")
df = df.replace('', np.nan)

df['publication_year'] = pd.to_numeric(df['publication_year'], errors='coerce')

df['publication_year'] = df['publication_year'].clip(lower=int(1800), upper=int(2026))

df['page_count'] = pd.to_numeric(df['page_count'], errors='coerce')
df.loc[df['page_count'] <= 0, 'page_count'] = np.nan

df['average_rating'] = pd.to_numeric(df['average_rating'], errors='coerce')
df.loc[
    (df['average_rating'] < 0) | (df['average_rating'] > 5),
    'average_rating'
] = np.nan

df['price_usd'] = pd.to_numeric(df['price_usd'], errors='coerce')
df.loc[df['price_usd'] < 0, 'price_usd'] = np.nan

df['sales_millions'] = pd.to_numeric(df['sales_millions'], errors='coerce')
df.loc[df['sales_millions'] < 0, 'sales_millions'] = np.nan




df['last_checkout'] = pd.to_datetime(df['last_checkout'], errors='coerce')

bool_map = {
    'true': True,
    'false': False,
    True: True,
    False: False
}

df['in_print'] = df['in_print'].map(bool_map)
df['available'] = df['available'].map(bool_map)



df["genre"] = df["genre"].str.title()
df["language"] = df["language"].str.title()
df["format"] = df["format"].str.title()
df["format"] = df["format"].str.title()
df["publisher"] = df['publisher'].str.title()


df = df.drop_duplicates(subset=['title', 'author'], keep='first')

# only dropping on more critical fields because according to my calculations, 
# there is a < 0.00013 chance (< 0.013%) for any given book to have only values
# that will not be dropped via dropna. 
required_fields = ['title', 'author', 'genre', 'publication_year', 'page_count', 'language']
df = df.dropna(subset=required_fields)

# could drop all of them with
# df = df.dropna()

print(df.head())

# ##################################################################
# #CHALLENGE: clean publisher_email so that they all end in '.com' #
# ##################################################################
 
df['publisher_email'] = df['publisher_email'].apply(
    lambda x: re.sub(r'(@.*)\..*', r'\1.com', x)
)
print(df.head())




                                 book_id          title     author  \
14  a04673a3-1adf-46f1-9fe5-fc181f0316fe   Book Title 9  Author 19   
17  852403b0-66b7-4019-933e-7425f5bec449  Book Title 11  Author 26   
21  74b41c20-f960-44ce-9ce0-5461cfd0bb6e  Book Title 19  Author 29   
38  8f72158f-826a-4792-bcf0-9fc6f50ac6a0  Book Title 10   Author 6   
42  00a36279-5380-4ed2-aff2-aa22aa6b5555  Book Title 11  Author 22   

              genre  publication_year  page_count  average_rating  \
14       Technology            1829.0       798.0             NaN   
17          History            2018.0       388.0             NaN   
21          Mystery            2006.0       710.0             NaN   
38  Science Fiction            1913.0       979.0            0.46   
42        Biography            1883.0       106.0             NaN   

   ratings_count  price_usd       publisher language      format in_print  \
14          None        NaN  Sunshine Media   French   Paperback     True   
17        

In [13]:
print("A")

A
